### ISSUE TITLE
TsunamiBuilder readme link is broken

### ISSUE THREAD

**Issue by spease** [jonhoo/tsunami#9]

**Comment by spease** [comment]
The docs also don't seem to exist for 0.5.1. Not sure if I'm just accessing things before a CI finished.

**Comment by jonhoo** [comment]
Yeah, that's a little unfortunate. It happens because of https://github.com/livioribeiro/cargo-readme/issues/18, which is a little out of my control. We *could* remove the link from `src/lib.rs`, but that'd be a little sad, or we could manually remove it from the (generated) `README.md`, but then we'd have to maintain it over time. I think the right thing to do here is probably just to monitor the `cargo-readme` issue for now.

**Comment by jonhoo** [comment]
As for the missing docs.rs page, I'm not sure what happened. I've reported it here: https://github.com/onur/docs.rs/issues/23#issuecomment-369052824

**Comment by jonhoo** [comment]
The docs.rs page is up now, so I'll close this :)
